### ISSUE TITLE
204 response code on DELETE requests?

### ISSUE THREAD

**Issue by jhugon61** [atomicjolt/lms_api#10]
Thanks for this very useful library.

I am running into an issue when generating a "DELETE_QUIZ_QUESTION" request. According to the documentation (https://canvas.instructure.com/doc/api/quiz_questions.html#method.quizzes/quiz_questions.destroy) and the live API, the response code returned on successful deletion will be 204.

The request I generate appears to be valid (the question does get deleted from the quiz on Canvas), but the gem raises an LMS::Canvas::InvalidAPIRequestException. Looking at the `/lib/lms/canvas.rb` file, the `check_result` method on line 188 appears to consider only 200 and 201 as valid response codes. Should 204 also be considered valid, at least in conjunction with DELETE verbs?

Let me know if I can provide additional information/traces as need be.

**Comment by jbasdf** [comment]
Thanks for finding that. A 204 is valid. We'll get it fixed.

**Comment by jbasdf** [comment]
Fixed in version v1.3.10

**Comment by jhugon61** [comment]
Thanks very much for the prompt response!
All the best,
~~~~~~~~~~~~~~~~~~~~~
Jacques Hugon
jacques.hugon@gmail.com
~~~~~~~~~~~~~~~~~~~~~
